package com.maven.flow.hibernate.dao;



/**
 * TblEmployeeInfo generated by MyEclipse - Hibernate Tools
 */

public class TblEmployeeInfo  implements java.io.Serializable {


    // Fields    

     private Long femployeeSn;
     private String femployeeIkey;
     private String femployeeName;
     private String floginName;
     private String floginPwd;
     private Long fdepartmentSn;
     private String fdepartmentName;
     private String fsex;
     private String fphone;
     private String faddress;
     private Integer fadminPositionId;
     private String fadminPositionName;
     private Integer ftechnicPositionId;
     private String ftechnicPositionName;
     private Integer fworkLogAwoke;
     private Integer fsendAuditAwoke;
     private Integer faddDataAwoke;
     private Long froleSn;
     private String froleName;
     private Long fsysRoleSn;
     private String fsysRoleName;
     private String fpower;
     private Integer fisLeader;
     private Byte fisDel;
     private Byte fisDisabled;
     private String fremark;
     private Integer forderBy;
     private Integer fallowAddPastWorkLog;


    // Constructors

    /** default constructor */
    public TblEmployeeInfo() {
    }

	/** minimal constructor */
    public TblEmployeeInfo(Long femployeeSn) {
        this.femployeeSn = femployeeSn;
    }
    
    /** full constructor */
    public TblEmployeeInfo(Long femployeeSn, String femployeeIkey, String femployeeName, String floginName, String floginPwd, Long fdepartmentSn, String fdepartmentName, String fsex, String fphone, String faddress, Integer fadminPositionId, String fadminPositionName, Integer ftechnicPositionId, String ftechnicPositionName, Integer fworkLogAwoke, Integer fsendAuditAwoke, Integer faddDataAwoke, Long froleSn, String froleName, Long fsysRoleSn, String fsysRoleName, String fpower, Integer fisLeader, Byte fisDel, Byte fisDisabled, String fremark, Integer forderBy, Integer fallowAddPastWorkLog) {
        this.femployeeSn = femployeeSn;
        this.femployeeIkey = femployeeIkey;
        this.femployeeName = femployeeName;
        this.floginName = floginName;
        this.floginPwd = floginPwd;
        this.fdepartmentSn = fdepartmentSn;
        this.fdepartmentName = fdepartmentName;
        this.fsex = fsex;
        this.fphone = fphone;
        this.faddress = faddress;
        this.fadminPositionId = fadminPositionId;
        this.fadminPositionName = fadminPositionName;
        this.ftechnicPositionId = ftechnicPositionId;
        this.ftechnicPositionName = ftechnicPositionName;
        this.fworkLogAwoke = fworkLogAwoke;
        this.fsendAuditAwoke = fsendAuditAwoke;
        this.faddDataAwoke = faddDataAwoke;
        this.froleSn = froleSn;
        this.froleName = froleName;
        this.fsysRoleSn = fsysRoleSn;
        this.fsysRoleName = fsysRoleName;
        this.fpower = fpower;
        this.fisLeader = fisLeader;
        this.fisDel = fisDel;
        this.fisDisabled = fisDisabled;
        this.fremark = fremark;
        this.forderBy = forderBy;
        this.fallowAddPastWorkLog = fallowAddPastWorkLog;
    }

   
    // Property accessors

    public Long getFemployeeSn() {
        return this.femployeeSn;
    }
    
    public void setFemployeeSn(Long femployeeSn) {
        this.femployeeSn = femployeeSn;
    }

    public String getFemployeeIkey() {
        return this.femployeeIkey;
    }
    
    public void setFemployeeIkey(String femployeeIkey) {
        this.femployeeIkey = femployeeIkey;
    }

    public String getFemployeeName() {
        return this.femployeeName;
    }
    
    public void setFemployeeName(String femployeeName) {
        this.femployeeName = femployeeName;
    }

    public String getFloginName() {
        return this.floginName;
    }
    
    public void setFloginName(String floginName) {
        this.floginName = floginName;
    }

    public String getFloginPwd() {
        return this.floginPwd;
    }
    
    public void setFloginPwd(String floginPwd) {
        this.floginPwd = floginPwd;
    }

    public Long getFdepartmentSn() {
        return this.fdepartmentSn;
    }
    
    public void setFdepartmentSn(Long fdepartmentSn) {
        this.fdepartmentSn = fdepartmentSn;
    }

    public String getFdepartmentName() {
        return this.fdepartmentName;
    }
    
    public void setFdepartmentName(String fdepartmentName) {
        this.fdepartmentName = fdepartmentName;
    }

    public String getFsex() {
        return this.fsex;
    }
    
    public void setFsex(String fsex) {
        this.fsex = fsex;
    }

    public String getFphone() {
        return this.fphone;
    }
    
    public void setFphone(String fphone) {
        this.fphone = fphone;
    }

    public String getFaddress() {
        return this.faddress;
    }
    
    public void setFaddress(String faddress) {
        this.faddress = faddress;
    }

    public Integer getFadminPositionId() {
        return this.fadminPositionId;
    }
    
    public void setFadminPositionId(Integer fadminPositionId) {
        this.fadminPositionId = fadminPositionId;
    }

    public String getFadminPositionName() {
        return this.fadminPositionName;
    }
    
    public void setFadminPositionName(String fadminPositionName) {
        this.fadminPositionName = fadminPositionName;
    }

    public Integer getFtechnicPositionId() {
        return this.ftechnicPositionId;
    }
    
    public void setFtechnicPositionId(Integer ftechnicPositionId) {
        this.ftechnicPositionId = ftechnicPositionId;
    }

    public String getFtechnicPositionName() {
        return this.ftechnicPositionName;
    }
    
    public void setFtechnicPositionName(String ftechnicPositionName) {
        this.ftechnicPositionName = ftechnicPositionName;
    }

    public Integer getFworkLogAwoke() {
        return this.fworkLogAwoke;
    }
    
    public void setFworkLogAwoke(Integer fworkLogAwoke) {
        this.fworkLogAwoke = fworkLogAwoke;
    }

    public Integer getFsendAuditAwoke() {
        return this.fsendAuditAwoke;
    }
    
    public void setFsendAuditAwoke(Integer fsendAuditAwoke) {
        this.fsendAuditAwoke = fsendAuditAwoke;
    }

    public Integer getFaddDataAwoke() {
        return this.faddDataAwoke;
    }
    
    public void setFaddDataAwoke(Integer faddDataAwoke) {
        this.faddDataAwoke = faddDataAwoke;
    }

    public Long getFroleSn() {
        return this.froleSn;
    }
    
    public void setFroleSn(Long froleSn) {
        this.froleSn = froleSn;
    }

    public String getFroleName() {
        return this.froleName;
    }
    
    public void setFroleName(String froleName) {
        this.froleName = froleName;
    }

    public Long getFsysRoleSn() {
        return this.fsysRoleSn;
    }
    
    public void setFsysRoleSn(Long fsysRoleSn) {
        this.fsysRoleSn = fsysRoleSn;
    }

    public String getFsysRoleName() {
        return this.fsysRoleName;
    }
    
    public void setFsysRoleName(String fsysRoleName) {
        this.fsysRoleName = fsysRoleName;
    }

    public String getFpower() {
        return this.fpower;
    }
    
    public void setFpower(String fpower) {
        this.fpower = fpower;
    }

    public Integer getFisLeader() {
        return this.fisLeader;
    }
    
    public void setFisLeader(Integer fisLeader) {
        this.fisLeader = fisLeader;
    }

    public Byte getFisDel() {
        return this.fisDel;
    }
    
    public void setFisDel(Byte fisDel) {
        this.fisDel = fisDel;
    }

    public Byte getFisDisabled() {
        return this.fisDisabled;
    }
    
    public void setFisDisabled(Byte fisDisabled) {
        this.fisDisabled = fisDisabled;
    }

    public String getFremark() {
        return this.fremark;
    }
    
    public void setFremark(String fremark) {
        this.fremark = fremark;
    }

    public Integer getForderBy() {
        return this.forderBy;
    }
    
    public void setForderBy(Integer forderBy) {
        this.forderBy = forderBy;
    }

    public Integer getFallowAddPastWorkLog() {
        return this.fallowAddPastWorkLog;
    }
    
    public void setFallowAddPastWorkLog(Integer fallowAddPastWorkLog) {
        this.fallowAddPastWorkLog = fallowAddPastWorkLog;
    }
   








}