package com.maven.flow.hibernate.dao;



/**
 * TblMenuBase generated by MyEclipse - Hibernate Tools
 */

public class TblMenuBase  implements java.io.Serializable {


    // Fields    

     private Integer fid;
     private String ffirstUrl;
     private String fcnName;


    // Constructors

    /** default constructor */
    public TblMenuBase() {
    }

	/** minimal constructor */
    public TblMenuBase(Integer fid) {
        this.fid = fid;
    }
    
    /** full constructor */
    public TblMenuBase(Integer fid, String ffirstUrl, String fcnName) {
        this.fid = fid;
        this.ffirstUrl = ffirstUrl;
        this.fcnName = fcnName;
    }

   
    // Property accessors

    public Integer getFid() {
        return this.fid;
    }
    
    public void setFid(Integer fid) {
        this.fid = fid;
    }

    public String getFfirstUrl() {
        return this.ffirstUrl;
    }
    
    public void setFfirstUrl(String ffirstUrl) {
        this.ffirstUrl = ffirstUrl;
    }

    public String getFcnName() {
        return this.fcnName;
    }
    
    public void setFcnName(String fcnName) {
        this.fcnName = fcnName;
    }
   








}