package com.maven.flow.hibernate.dao;

/**
 * TblProcessAccess generated by MyEclipse Persistence Tools
 */

public class TblProcessAccess implements java.io.Serializable {

	/**
	 * 角色类型：角色
	 */
	public static final int ROLE_TYPE_ROLE = 0;

	/**
	 * 角色类型：员工
	 */
	public static final int ROLE_TYPE_USER = 1;
	// Fields

	private Integer processAccessRecordId;

	private Integer processId;

	private Integer roleId;

	private Integer roleType;

	// Constructors

	/** default constructor */
	public TblProcessAccess() {
	}

	/** full constructor */
	public TblProcessAccess(Integer processAccessRecordId, Integer processId,
			Integer roleId, Integer roleType) {
		this.processAccessRecordId = processAccessRecordId;
		this.processId = processId;
		this.roleId = roleId;
		this.roleType = roleType;
	}

	// Property accessors

	public Integer getProcessAccessRecordId() {
		return this.processAccessRecordId;
	}

	public void setProcessAccessRecordId(Integer processAccessRecordId) {
		this.processAccessRecordId = processAccessRecordId;
	}

	public Integer getProcessId() {
		return this.processId;
	}

	public void setProcessId(Integer processId) {
		this.processId = processId;
	}

	public Integer getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	public Integer getRoleType() {
		return this.roleType;
	}

	public void setRoleType(Integer roleType) {
		this.roleType = roleType;
	}

}