package com.maven.flow.hibernate.dao;



/**
 * TblProcessPeople generated by MyEclipse - Hibernate Tools
 */

public class TblProcessPeople  implements java.io.Serializable {
	
	 
    // Fields    
	 
     private Integer fsn;
     private Integer processId;
     private String processName;
     private Integer peopleType;//4:会签的用户。
     private String realFsn;
     private String realValue;
     
     

    // Constructors

    /** default constructor */
    public TblProcessPeople() {
    }

    
    /** full constructor */
    public TblProcessPeople(Integer processId, String processName, Integer peopleType, String realFsn,String realValue) {
        this.processId = processId;
        this.processName = processName;
        this.peopleType = peopleType;
        this.realFsn = realFsn;
        this.realValue=realValue;
    }
    
   
    // Property accessors

    public String getRealValue() {
		return realValue;
	}


	public void setRealValue(String realValue) {
		this.realValue = realValue;
	}


	public Integer getFsn() {
        return this.fsn;
    }
    
    public void setFsn(Integer fsn) {
        this.fsn = fsn;
    }

    public Integer getProcessId() {
        return this.processId;
    }
    
    public void setProcessId(Integer processId) {
        this.processId = processId;
    }

    public String getProcessName() {
        return this.processName;
    }
    
    public void setProcessName(String processName) {
        this.processName = processName;
    }

    public Integer getPeopleType() {
        return this.peopleType;
    }
    
    public void setPeopleType(Integer peopleType) {
        this.peopleType = peopleType;
    }

    public String getRealFsn() {
        return this.realFsn;
    }
    
    public void setRealFsn(String realFsn) {
        this.realFsn = realFsn;
    }
   








}