package com.maven.flow.instance.hibernate.dao;

import java.util.Date;


/**
 * TblJobBase generated by MyEclipse - Hibernate Tools
 */

public class TblJobBase   implements java.io.Serializable,Cloneable{
    /**
     * 状态：处理中
     */
    public static final int STATUS_HANDLING = 0;

    /**
     * 状态：已完成
     */
    public static final int STATUS_COMPLETE = 1;

    /**
     * 状态：异常
     */
    public static final int STATUS_EXCEPTION = 2;
    
    /**
     * 状态：撤回
     */
    public static final int STATUS_BACK = 3;
    
    /**
     * 状态：调整
     */
    public static final int STATUS_CHANGE = 4;

    // Fields    

     private Long fsn;
     private Date fbeginTime;
     private Date fendTime;
     private Integer fjobStatus;
     private Long ftaskId;
     private Integer fprocessId;
     private Integer fappId;
     private Date forderTime;
     private Integer fisAsynchronism;
     private Integer fsubmitOption;
     private Integer fishidden;
     private Integer fifOpen;
     private Date forderDate;

     public TblJobBase clone(){
     	try{
     		return (TblJobBase)super.clone();
     	}catch(Exception e){
     		e.printStackTrace();
     		return null;
     	}
  }
    // Constructors

    /** default constructor */
    public TblJobBase() {
    }

	/** minimal constructor */
    public TblJobBase(Long fsn) {
        this.fsn = fsn;
    }
    
    /** full constructor */
    public TblJobBase(Long fsn, Date fbeginTime, Date fendTime, Integer fjobStatus, Long ftaskId, Integer fprocessId, Integer fappId, Date forderTime, Integer fisAsynchronism, Integer fsubmitOption, Integer fishidden, Integer fifOpen, Date forderDate) {
        this.fsn = fsn;
        this.fbeginTime = fbeginTime;
        this.fendTime = fendTime;
        this.fjobStatus = fjobStatus;
        this.ftaskId = ftaskId;
        this.fprocessId = fprocessId;
        this.fappId = fappId;
        this.forderTime = forderTime;
        this.fisAsynchronism = fisAsynchronism;
        this.fsubmitOption = fsubmitOption;
        this.fishidden = fishidden;
        this.fifOpen = fifOpen;
        this.forderDate = forderDate;
    }

   
    // Property accessors

    public Long getFsn() {
        return this.fsn;
    }
    
    public void setFsn(Long fsn) {
        this.fsn = fsn;
    }

    public Date getFbeginTime() {
        return this.fbeginTime;
    }
    
    public void setFbeginTime(Date fbeginTime) {
        this.fbeginTime = fbeginTime;
    }

    public Date getFendTime() {
        return this.fendTime;
    }
    
    public void setFendTime(Date fendTime) {
        this.fendTime = fendTime;
    }

    public Integer getFjobStatus() {
        return this.fjobStatus;
    }
    
    public void setFjobStatus(Integer fjobStatus) {
        this.fjobStatus = fjobStatus;
    }

    public Long getFtaskId() {
        return this.ftaskId;
    }
    
    public void setFtaskId(Long ftaskId) {
        this.ftaskId = ftaskId;
    }

    public Integer getFprocessId() {
        return this.fprocessId;
    }
    
    public void setFprocessId(Integer fprocessId) {
        this.fprocessId = fprocessId;
    }

    public Integer getFappId() {
        return this.fappId;
    }
    
    public void setFappId(Integer fappId) {
        this.fappId = fappId;
    }

    public Date getForderTime() {
        return this.forderTime;
    }
    
    public void setForderTime(Date forderTime) {
        this.forderTime = forderTime;
    }

    public Integer getFisAsynchronism() {
        return this.fisAsynchronism;
    }
    
    public void setFisAsynchronism(Integer fisAsynchronism) {
        this.fisAsynchronism = fisAsynchronism;
    }

    public Integer getFsubmitOption() {
        return this.fsubmitOption;
    }
    
    public void setFsubmitOption(Integer fsubmitOption) {
        this.fsubmitOption = fsubmitOption;
    }

    public Integer getFishidden() {
        return this.fishidden;
    }
    
    public void setFishidden(Integer fishidden) {
        this.fishidden = fishidden;
    }

    public Integer getFifOpen() {
        return this.fifOpen;
    }
    
    public void setFifOpen(Integer fifOpen) {
        this.fifOpen = fifOpen;
    }

    public Date getForderDate() {
        return this.forderDate;
    }
    
    public void setForderDate(Date forderDate) {
        this.forderDate = forderDate;
    }
   








}