package com.maven.flow.instance.hibernate.dao;

import java.util.Date;


/**
 * TblMiniJob generated by MyEclipse - Hibernate Tools
 */

public class TblMiniJob  implements java.io.Serializable,Cloneable {

    /**
     * 状态：处理中
     */
    public static final int STATUS_HANDLING = 0;

    /**
     * 状态：已完成
     */
    public static final int STATUS_COMPLETE = 1;

    /**
     * 状态：异常
     */
    public static final int STATUS_EXCEPTION = 2;
    
    /**
     * 状态：撤回
     */
    public static final int STATUS_BACK = 3;
    
    // Fields    

     private Long fsn;
     private Long fjobId;
     private Integer fminiJobUserId;
     private String fminiJobUserName;
     private Date fbeginTime;
     private Date fendTime;
     private Integer fminiJobStatus;
     private Integer fisAsynchronism;
     private String fsubmitOption;
     private Integer forderBy;
     private String forderbyNote;
     private Integer fisFromHuiQian;

 	
     public TblMiniJob clone(){
        	try{
        		return (TblMiniJob)super.clone();
        	}catch(Exception e){
        		e.printStackTrace();
        		return null;
        	}
     }
    // Constructors

    /** default constructor */
    public TblMiniJob() {
    }

	/** minimal constructor */
    public TblMiniJob(Long fsn) {
        this.fsn = fsn;
    }
    
    /** full constructor */
    public TblMiniJob(Long fsn, Long fjobId, Integer fminiJobUserId, String fminiJobUserName, Date fbeginTime, Date fendTime, Integer fminiJobStatus, Integer fisAsynchronism, String fsubmitOption, Integer forderBy, String forderbyNote, Integer fisFromHuiQian) {
        this.fsn = fsn;
        this.fjobId = fjobId;
        this.fminiJobUserId = fminiJobUserId;
        this.fminiJobUserName = fminiJobUserName;
        this.fbeginTime = fbeginTime;
        this.fendTime = fendTime;
        this.fminiJobStatus = fminiJobStatus;
        this.fisAsynchronism = fisAsynchronism;
        this.fsubmitOption = fsubmitOption;
        this.forderBy = forderBy;
        this.forderbyNote = forderbyNote;
        this.fisFromHuiQian = fisFromHuiQian;
    }

   
    // Property accessors



    public Long getFjobId() {
		return fjobId;
	}

	public void setFjobId(Long fjobId) {
		this.fjobId = fjobId;
	}

	public Long getFsn() {
		return fsn;
	}

	public void setFsn(Long fsn) {
		this.fsn = fsn;
	}

	public Integer getFminiJobUserId() {
        return this.fminiJobUserId;
    }
    
    public void setFminiJobUserId(Integer fminiJobUserId) {
        this.fminiJobUserId = fminiJobUserId;
    }

    public String getFminiJobUserName() {
        return this.fminiJobUserName;
    }
    
    public void setFminiJobUserName(String fminiJobUserName) {
        this.fminiJobUserName = fminiJobUserName;
    }

    public Date getFbeginTime() {
        return this.fbeginTime;
    }
    
    public void setFbeginTime(Date fbeginTime) {
        this.fbeginTime = fbeginTime;
    }

    public Date getFendTime() {
        return this.fendTime;
    }
    
    public void setFendTime(Date fendTime) {
        this.fendTime = fendTime;
    }

    public Integer getFminiJobStatus() {
        return this.fminiJobStatus;
    }
    
    public void setFminiJobStatus(Integer fminiJobStatus) {
        this.fminiJobStatus = fminiJobStatus;
    }

    public Integer getFisAsynchronism() {
        return this.fisAsynchronism;
    }
    
    public void setFisAsynchronism(Integer fisAsynchronism) {
        this.fisAsynchronism = fisAsynchronism;
    }

    public String getFsubmitOption() {
        return this.fsubmitOption;
    }
    
    public void setFsubmitOption(String fsubmitOption) {
        this.fsubmitOption = fsubmitOption;
    }

    public Integer getForderBy() {
        return this.forderBy;
    }
    
    public void setForderBy(Integer forderBy) {
        this.forderBy = forderBy;
    }

    public String getForderbyNote() {
        return this.forderbyNote;
    }
    
    public void setForderbyNote(String forderbyNote) {
        this.forderbyNote = forderbyNote;
    }

    public Integer getFisFromHuiQian() {
        return this.fisFromHuiQian;
    }
    
    public void setFisFromHuiQian(Integer fisFromHuiQian) {
        this.fisFromHuiQian = fisFromHuiQian;
    }
   








}